### ISSUE TITLE
amass enum -passive finds more subdomains than active

### ISSUE THREAD

**Issue by fxa** [OWASP/Amass#427]
e.g.
`amass enum -passive -d orbiter.de 2>/dev/null
orbiter.de
smtp.orbiter.de
mail.orbiter.de
owncloud.orbiter.de
www.orbiter.de
netfarm.orbiter.de
eng.orbiter.de
`
`amass enum -active -brute -d orbiter.de 2>/dev/null
orbiter.de
www.orbiter.de
`
The smtp.orbiter.de was not very hard to detect, because the MX record points to it, but -active did not find it.
Is this a bug? 
Or do I really have to run active and passive mode to see all of the subdomains?

**Comment by caffix** [comment]
Great catch! It appears that root domain names were not always being investigated as thoroughly as proper subdomain names are. This has been fixed and will be in the upcoming release

**Comment by fxa** [comment]
Hello caffix,
thanks for Your quick answer!
For now I am just doing both, active and passive. And i have a lot of candidates, where the result sets differ (in both directions). I will add a check, that active should >= passive. So after I installed Your release, I will do a lot of tests (That will take some days, because the scripts are very slow).
I will give feed back then!

**Comment by caffix** [comment]
This issue will close automatically when the fixes are merged with the master branch, but perhaps you can bring your findings to our Discord server for further discussion? I appreciate it

**Comment by fxa** [comment]
The bug is still there in v3.7.3!
Even with the provided example.
The active mode now detects smtp.orbiter.de, but still fails with mail.orbiter.de, which the passive mode finds
